// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef CtrlServoTeste_h
#define CtrlServoTeste_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include "SerialPort.h"

/**
 cria classe do controle do servo
*/
class ControleServoTeste {
  SerialPort serial;
public:
  ControleServoTeste();
private:
  Fl_Double_Window *UmaJanela;
  Fl_Dial *potenciometro;
  inline void cb_potenciometro_i(Fl_Dial*, void*);
  static void cb_potenciometro(Fl_Dial*, void*);
  Fl_Value_Slider *slider;
  inline void cb_slider_i(Fl_Value_Slider*, void*);
  static void cb_slider(Fl_Value_Slider*, void*);
  Fl_Button *Ok;
  inline void cb_Ok_i(Fl_Button*, void*);
  static void cb_Ok(Fl_Button*, void*);
  Fl_Light_Button *luz;
  inline void cb_luz_i(Fl_Light_Button*, void*);
  static void cb_luz(Fl_Light_Button*, void*);
public:
  void MyShow();
  void close();
private:
  void atualizar(double valor);
  void converca();
  void conect();
};
#endif
