// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "CtrlServoTeste.h"

void ControleServoTeste::cb_potenciometro_i(Fl_Dial*, void*) {
  this -> atualizar(this -> potenciometro -> value());
}
void ControleServoTeste::cb_potenciometro(Fl_Dial* o, void* v) {
  ((ControleServoTeste*)(o->parent()->user_data()))->cb_potenciometro_i(o,v);
}

void ControleServoTeste::cb_slider_i(Fl_Value_Slider*, void*) {
  this -> atualizar(this -> slider -> value());
}
void ControleServoTeste::cb_slider(Fl_Value_Slider* o, void* v) {
  ((ControleServoTeste*)(o->parent()->user_data()))->cb_slider_i(o,v);
}

void ControleServoTeste::cb_Ok_i(Fl_Button*, void*) {
  this -> converca();
}
void ControleServoTeste::cb_Ok(Fl_Button* o, void* v) {
  ((ControleServoTeste*)(o->parent()->user_data()))->cb_Ok_i(o,v);
}

void ControleServoTeste::cb_luz_i(Fl_Light_Button*, void*) {
  this -> conect();
}
void ControleServoTeste::cb_luz(Fl_Light_Button* o, void* v) {
  ((ControleServoTeste*)(o->parent()->user_data()))->cb_luz_i(o,v);
}

/**
 metodo construtor
*/
ControleServoTeste::ControleServoTeste() {
  { UmaJanela = new Fl_Double_Window(300, 350, "Controle Servo");
    UmaJanela->user_data((void*)(this));
    { potenciometro = new Fl_Dial(50, 20, 200, 200, "L/R");
      potenciometro->box(FL_PLASTIC_ROUND_UP_BOX);
      potenciometro->color((Fl_Color)1);
      potenciometro->labelfont(4);
      potenciometro->maximum(180);
      potenciometro->step(1);
      potenciometro->callback((Fl_Callback*)cb_potenciometro);
    } // Fl_Dial* potenciometro
    { slider = new Fl_Value_Slider(50, 250, 200, 25);
      slider->type(1);
      slider->box(FL_PLASTIC_UP_BOX);
      slider->color((Fl_Color)4);
      slider->maximum(180);
      slider->step(1);
      slider->callback((Fl_Callback*)cb_slider);
    } // Fl_Value_Slider* slider
    { Ok = new Fl_Button(120, 291, 60, 30, "OK!");
      Ok->box(FL_PLASTIC_THIN_UP_BOX);
      Ok->color((Fl_Color)62);
      Ok->labelfont(4);
      Ok->callback((Fl_Callback*)cb_Ok);
    } // Fl_Button* Ok
    { luz = new Fl_Light_Button(45, 290, 60, 30, " link");
      luz->box(FL_PLASTIC_DOWN_BOX);
      luz->labelfont(4);
      luz->callback((Fl_Callback*)cb_luz);
    } // Fl_Light_Button* luz
    UmaJanela->end();
  } // Fl_Double_Window* UmaJanela
}
