// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef CtrlTorreta_h
#define CtrlTorreta_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Button.H>
#include "SerialPort.h" //<<comunicacao serial

/**
 classe legal >=p
*/
class CtrlTorreta {
public:
  CtrlTorreta();
  Fl_Double_Window *window_Tctrl;
private:
  Fl_Dial *ud_dial;
  Fl_Dial *lr_dial;
  inline void cb_FIRE_i(Fl_Button*, void*);
  static void cb_FIRE(Fl_Button*, void*);
public:
  void show();
  void close();
private:
  void fire();
};
#endif
